version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_BINDING_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_FILE}:${REDIS_CONFIG_PATH}
    command: redis-server ${REDIS_CONFIG_PATH} --requirepass "${REDIS_PASSWORD}"
    restart: always
  go-app:
    build:
      context: ./go-app
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - ${SERVER_BINDING_PORT}:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always